# Generated by Django 4.2 on 2023-06-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_bio_user_profile_photo_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="static/My project (10).png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
